def get_sample_data():
    """
    Returns a sample dataset aligned with the Player model.
    """
    return [
        {
            "id": 1,
            "name": "Sample Player 1",
            "team": "Team A",
            "nationality": "Country X",
            "position": "Forward",
            "age": 25,
            "height": 180.5,
            "weight": 75.0,
            "matches": 30,
            "starts": 28,
            "mins": 2500,
            "goals": 15,
            "assists": 10,
            "passes_attempted": 500,
            "perc_passes_completed": 85.0,
            "penalty_goals": 2,
            "penalty_attempted": 3,
            "xg": 12.5,
            "xa": 8.3,
            "yellow_cards": 3,
            "red_cards": 0,
        },
        {
            "id": 2,
            "name": "Sample Player 2",
            "team": "Team B",
            "nationality": "Country Y",
            "position": "Midfielder",
            "age": 28,
            "height": 175.0,
            "weight": 70.0,
            "matches": 32,
            "starts": 30,
            "mins": 2700,
            "goals": 8,
            "assists": 12,
            "passes_attempted": 600,
            "perc_passes_completed": 88.0,
            "penalty_goals": 1,
            "penalty_attempted": 1,
            "xg": 10.0,
            "xa": 10.5,
            "yellow_cards": 2,
            "red_cards": 1,
        },
    ]